# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'AlexIronsourceSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
#  pod 'AnyThinkiOS','6.2.81'
#  pod 'IronSourceSDK'
  # Pods for IronsourceCustomSDK

end

target 'AlexIronsourceSDKAdapter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
#  pod 'AnyThinkiOS','6.2.81'
#  pod 'IronSourceSDK'
  # Pods for IronsourceSDKAdapter

end
